BlockSearch.MVC/Models/ErrorViewModel.cs
using System;

namespace BlockSearch.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlockSearch.MVC/Models/TransactionModel.cs
namespace BlockSearch.MVC.Models
{
    public class TransactionModel
    {
        public string BlockHash { get; set; }
        public string BlockNumber { get; set; }
        public string Gas { get; set; }
        public string Hash { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Value { get; set; }
    }
}

BlockSearch.MVC/Models/TransactionSearchModel.cs
using BlockSearch.Common.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlockSearch.MVC.Models
{
    public class TransactionSearchModel
    {
        [Display(Name = "Block Number")]
        [Required(ErrorMessage = "Block Number is Required")]
        [Range(0, int.MaxValue, ErrorMessage = "Block Number must be a positive number")]
        public int? BlockNumber { get; set; }

        [Display(Name = "Address")]
        public string Address { get; set; }

        [Display(Name = "Crypto Type")]
        public CryptoType? Crypto { get; set; }

        public List<TransactionModel> Transactions { get; set; } = new List<TransactionModel>();

        public string ErrorMessage { get; set; }
    }
}

BlockSearch.MVC/Controllers/HomeController.cs
using BlockSearch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlockSearch.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlockSearch.MVC/Controllers/TransactionSearchController.cs
using BlockSearch.Application;
using BlockSearch.Common.Enums;
using BlockSearch.Common.Exceptions;
using BlockSearch.Common.Models;
using BlockSearch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BlockSearch.MVC.Controllers
{
    public class TransactionSearchController : Controller
    {
        private IBlockSearchService _blockSearchService;

        public TransactionSearchController(IBlockSearchService blockSearchService)
        {
            _blockSearchService = blockSearchService;
        }

        // GET: TransactionSearchController
        public ActionResult Index()
        {
            var searchModel = new TransactionSearchModel()
            {
                Crypto = CryptoType.Ethereum // defaulting to Eth
            };
            return View(searchModel);
        }

        // POST: TransactionSearchController
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(TransactionSearchModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Crypto = CryptoType.Ethereum;
                return View(model);
            }

            try
            {
                var block = await _blockSearchService.GetAddressTransactionsInBlock(model.Crypto, model.BlockNumber, model.Address);
                return View(BuildSuccesfulResponse(block));
            }
            catch(Exception ex)
            {
                if (CanShowExceptionMessageToUser(ex))
                    return View(BuildErrorResponse(ex.Message));
                
                return View(BuildErrorResponse("An unknown error has occurred."));
            }
        }

        private TransactionSearchModel BuildSuccesfulResponse(Block block)
        {
            return new TransactionSearchModel()
            {
                BlockNumber = int.Parse(block.Number),
                Address = block.Address,
                Crypto = block.Crypto,
                Transactions = block.Transactions.Select(x => new TransactionModel()
                {
                    BlockHash = x.BlockHash,
                    BlockNumber = x.BlockNumber,
                    From = x.From,
                    To = x.To,
                    Hash = x.Hash,
                    Gas = x.Gas,
                    Value = x.Value
                }).ToList()
            };
        }

        private TransactionSearchModel BuildErrorResponse(string message)
        {
            return new TransactionSearchModel()
            {
                Crypto = CryptoType.Ethereum,
                ErrorMessage = message
            };
        }

        private bool CanShowExceptionMessageToUser(Exception ex)
        {
            return
                (ex is BlockNotFoundException)
                || (ex is InvalidInputException);
        }
    }
}

BlockSearch.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlockSearch.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlockSearch.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlockSearch.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionSearch" asp-action="Index">Transaction Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BlockSearch.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlockSearch.MVC/Views/TransactionSearch/Index.cshtml
@model TransactionSearchModel
@{
    string PageTitle = $"Transaction Search - {Model.Crypto.ToString()}";
    ViewData["Title"] = PageTitle;
}

<div class="text-left">
    <h1 class="display-4">@(PageTitle)</h1>
</div>

<div class="container">
    @using (Html.BeginForm("Index", "TransactionSearch", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Crypto)

        <fieldset>
            <div>
                <div>
                    <div class="alert alert-info" role="alert">
                        <p>Use this tool to search for transactions within a block.</p>
                        <p>If an address if provided, the transaction list can be filtered down to only show transactions where the address was a participant.</p>
                    </div>
                </div>
                <div>
                    @{
                        if (!string.IsNullOrEmpty(Model.ErrorMessage))
                        {
                            <div class="alert alert-danger" role="alert">@(Model.ErrorMessage)</div>
                        }
                    }
                </div>

                <div class="mb-3">
                    @Html.LabelFor(m => m.BlockNumber, new { @class = "form-label" })
                    @Html.TextBoxFor(m => m.BlockNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BlockNumber, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    @Html.LabelFor(m => m.Address, new { @class = "form-label" })
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </fieldset>
    }
</div>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Block Hash</th>
                <th scope="col">Block Number</th>
                <th scope="col">Gas</th>
                <th scope="col">Hash</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            @{
                int rowCount = 1;
                foreach(var transaction in Model.Transactions)
                {
                    <tr>
                        <td scope="col">@(rowCount)</td>
                        <td scope="col">@(transaction.BlockHash)</td>
                        <td scope="col">@(transaction.BlockNumber)</td>
                        <td scope="col">@(transaction.Gas)</td>
                        <td scope="col">@(transaction.Hash)</td>
                        <td scope="col">@(transaction.From)</td>
                        <td scope="col">@(transaction.To)</td>
                        <td scope="col">@(transaction.Value)</td>
                    </tr>
                    rowCount++;
                }
            }
        </tbody>
    </table>
</div>